env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react

settings:
  react:
    version: 'detect'

rules:
  semi: ['error', 'never']
  'no-console': 0
  'no-param-reassign': 0
  'no-unused-vars': 1
  'no-underscore-dangle': [2, { allow: ['__filename', '__dirname'] }]
  'react/prop-types': 0
  'react/react-in-jsx-scope': 0
  'react/function-component-definition': [2, { namedComponents: 'arrow-function' }]
  'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }]

  padding-line-between-statements:
    - 'error'
    - blankLine: 'always'
      prev: 'block'
      next: '*'
    - blankLine: 'always'
      prev: 'block-like'
      next: '*'